language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tarunsuneja/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tarunsuneja/docker-react npm run test

deploy:
  provider: elsaticbeanstalk
  region: "ap-south-1"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-042921395286"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
